spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recipe_discovery?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root      # sửa theo máy bạn
    password: 01218923570Aa     # sửa theo máy bạn
  jpa:
    hibernate:
      ddl-auto: none    # vì bạn đã tạo sẵn bảng
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
  thymeleaf:
    cache: false

server:
  port: 8080
